//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avancada.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvanBDContainer : DbContext
    {
        public AvanBDContainer()
            : base("name=AvanBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Refeicao> Refeicao { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Transacao> Transacao { get; set; }
        public DbSet<Usuario> UsuarioSet { get; set; }
        public DbSet<SAC> SACSet { get; set; }
    }
}
