//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avancada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardapio
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public bool Aprovacao { get; set; }
        public int NutricionistaId { get; set; }
        public int RefeicaoId { get; set; }
    
        public virtual Nutricionista Nutricionista { get; set; }
        public virtual Refeicao Refeicao { get; set; }
    }
}
