//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avancada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refeicao
    {
        public int Id { get; set; }
        public string Principal { get; set; }
        public string Salada { get; set; }
        public string Bebida { get; set; }
        public string Sobremesa { get; set; }
        public string Vegetariana { get; set; }
        public int UsuarioId { get; set; }
        public string Data { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
