//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avancada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAC
    {
        public int Id { get; set; }
        public string mensagem { get; set; }
        public string data { get; set; }
        public string tipo { get; set; }
        public string tipoclientr { get; set; }
        public string Property1 { get; set; }
    }
}
