//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avancada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAC
    {
        public int IdSAC { get; set; }
        public string Mensagem { get; set; }
        public System.DateTime Data { get; set; }
        public string Tipo { get; set; }
        public int UsuarioIdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
