//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avancada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Transacao = new HashSet<Transacao>();
            this.Refeicao = new HashSet<Refeicao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string CPF { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Transacao> Transacao { get; set; }
        public virtual ICollection<Refeicao> Refeicao { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
